### ISSUE TITLE
transformation and some suggestions

### ISSUE THREAD

**Issue by mimisikai** [RGLab/flowCore#104]
I'm not sure whether it's a legitimate feature,  but from my side, I feel some gating failures may due to incorrected or improperly transformation. So far, the bi-transformation is based on one sample that picked up arbitrarily. For some data sets, especially longitudinal studies, the first sample and last sample maybe various, i.e. machine voltage, compensation et al, even if we've tried best to keep the consistency, but those unexpected changes may jump up sometimes. So, my concern, applying the transformation from one sample to spread to all samples, is appropriate or not?  @mikejiang @gfinak 

The opencyto is awesome package, but I have to say, the tutorials have to be improved if you want to more people without any knowledge about R and coding to utilize this tool in their work. I suggest to assume the users are zero background, and teach them step by step and from very beginning in order to make sure everybody would be able to establish their own pipeline without frequently request basis questions and assistance from your side. One more, the tutorials and workshop info spread out everywhere,  would you be able to deposit and consolidate all those useful tutorials et al in ONE website? @raphg

**Comment by mikejiang** [comment]
Still debating within myself about the idea of sample-specific transformation parameters.
Technically it is fairly straightforward: we can extend existing s3 method `estimateLogicle.GatingHierarchy` introduced by #206 with `estimateLogicle.GatingSet` that iterates through samples to do the sample-by-sample logicle parameter estimation and then return a named list of `transformerList`, which can be applied by `transform(gs, lostOfTrans)` and stored at R level (`transformation` slot).
Seemingly it does provide the flexibility of the infrastructure so that transformation can be optionally adjusted at sample level.
However , as @gfinak said, data won't be fully comparable across samples (especially MFI).
Imagine such `GatingSet` is archived and delivered to another user without the prior warning about the issues of different scales within the data set, confusion is almost certain to occur down the road.

**Comment by gfinak** [comment]
One possibility is to update the `print` and `summary` methods for a GatingSet, to output something like:

When the same transformation parameters are used:
"MFIs are comparable across samples."
or
When different transformation parameters are used:
"Uses a heterogeneous transformation. MFIs are not comparable across samples."

**Comment by mikejiang** [comment]
@mimisikai , I ended up adding support for this feature by allowing passing a list of `transformerList` to `transform(gs, trans)` call. Check out the latest flowWorkspace, ncdfFlow and flowCore from github trunk

**Comment by gfinak** [comment]
Can this be closed?

**Comment by mikejiang** [comment]
sure
