### ISSUE TITLE
as.flowSet error

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#115]
Hi,
Sounds odds but I will go on with flowSet()
```
> data("GvHD")
> flowSet(GvHD[[1]])
A flowSet with 1 experiments.

  column names:
  FSC-H SSC-H FL1-H FL2-H FL3-H FL2-A FL4-H Time
> as.flowSet(GvHD[[1]])
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'sampleNames' for signature '"flowFrame"'
> packageVersion("flowCore")
[1] '1.46.1'
```

**Comment by gfinak** [comment]
Thanks for reporting this.

**Comment by SamGG** [comment]
I don't know if it is related or I am wrong:
```
> as.flowSet(list(GvHD[[1]], GvHD[[2]], GvHD[[3]]))
Error in names(from) <- paste("V", seq(1, length(from)), sep = "") :
    'names' attribute [2] must be the same length as the vector [0]
```
Thanks

**Comment by gfinak** [comment]
Just did some investigation, I find `as.flowSet` defined in the package `ncdfFlowSet` not `flowCore` and it's documented as:
> convert from a 'ncdfFlowSet' to a 'flowSet'

so I think the issue you're running into is caused by incorrect method dispatch. 
In fact, when I run your code I get:
``` 
library(flowCore)
as.flowSet(GvHD[[1]])
#> Error in as.flowSet(GvHD[[1]]): could not find function "as.flowSet"
```
since `as.flowSet` is not defined for `flowFrame` objects.
This is with:
```
packageVersion("flowCore")
[1] ‘1.47.4’
```

**Comment by SamGG** [comment]
Thanks for your feedback. I will update my flowCore installation.
I found the following code that let me think that the coercion is done in flowCore. But I am not an expert.
https://github.com/RGLab/flowCore/blob/6fa20141ab6c4d5f1c4f72495317c0ea216c31e6/R/coerce.R#L275-L280

**Comment by gfinak** [comment]
The following will work:
```
as(GvHD[[1]],"flowSet")

A flowSet with 1 experiments.

  column names:
  FSC-H SSC-H FL1-H FL2-H FL3-H FL2-A FL4-H Time
```

**Comment by mikejiang** [comment]
Maybe we should deprecate `as.flowSet` and define ` setAs(from="ncdfFlowSet", to="flowSet", def=function(from)` to avoid future confusion? 
It shouldn't have too much impact on user side since `as.flowSet` is only having limited usage within `ncdfFlowSet` as far as I see

**Comment by gfinak** [comment]
Agreed.

**Comment by mikejiang** [comment]
looks like it is problematic to overwrite the default coerce method 
```r
> nc1 <- ncdfFlowSet(GvHD[1:4])
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
```
Probably because the `flowSet` class is the superClass of  `ncdfFlowSet`  and during the process of constructing a new `ncdfFlowSet` the `validity` method of `flowSet` is invoked.And within that method a couple of s4 accessor methods are also invoked which further invoked the `coerce` method itself and causes the chain effect of infinite recursive calls.

I think this might be the reason we implemented non-standard coercion API `as.flowSet` back then instead.

**Comment by SamGG** [comment]
Thanks for `as(GvHD[[1]],"flowSet")`.
Thanks for maintaining and improving the invaluable flowCore package.
