### ISSUE TITLE
write.FCS() behaving differently in different development environments

### ISSUE THREAD

**Issue by Gesseca** [RGLab/flowCore#116]
Hello,

I am having some issues with the write.FCS() function. In my code, I add clustering results to flowframes by binding another column to the data matrix (which works perfectly), and then adding the kewords to the parameters and description. When I look at the description manually, the information is there, but the new column/channel disappears when I view the FCS files in Cytobank. 

My colleague suggested I try using a docker container of his environment, since this problem mysteriously didn't happen on his computer. I tried it. The only problem is that now the new column/channel shows up as expected, but some of the channel descriptions are missing. The code wasn't changed at all. 

I decided to inspect the the FCS files directly, by looking at the header text. Now some differences became clear. In my home computer environment, information was separated with pipes (|), but the files generated from running my script in the docker container had backslashes instead of pipes. Also, there was a gap after the $PxS keywords in the files created by the docker container "\ \". For some reason there were two backslashes with a space and nothing there. I assume that's what's causing the descriptions not to show up properly. 

I'm not sure which development environment to choose now, since they both have problems. I was wondering if there is a way to overcome this inconsistency, like somehow control whether write.FCS is using pipes or backslashes, or to perhaps troubleshoot why there is a mysterious empty space in the files with the backslashes after the $PxS keywords. 

Any help with this would be much appreciated,

Gesseca

**Comment by gfinak** [comment]
Could you paste your code here, or provide a reproducible example?

**Comment by gfinak** [comment]
Also could you provide the `Session.info()` for both the environments?

**Comment by mikejiang** [comment]
`delimiter` has been changed to `|` in e57d42948c759313554488aca144f8e77eeb2e3c
So if you update your flowCore to the latest release, then both windows and linux/mac should behave the same at least.

**Comment by Gesseca** [comment]
Mikejiang,
Ok, I will try that!
gfinak, yes, I will paste my code. What is Session.info()? Do I just type that in the terminal after running the session? I have been running the one on my home environment through Rstudio- will that affect it? I will paste my code in a minute. Thanks, guys!

**Comment by Gesseca** [comment]
I believe I already have the latest version of FlowCore...

**Comment by Gesseca** [comment]
I just downloaded the most recent version of FlowCore, both to my home environment (mac) and the docker environment (PC-based). On the PC-docker environment I am still getting backslashes instead of pipes. I thought the new version was supposed to give only pipes. Is there something specific I have to download? 

mikejiang, I clicked on this link you sent: e57d429, but I don't know what to do with it. I'm a relatively new user to GitHub...

**Comment by SamGG** [comment]
Hi, run `sessionInfo()` in the R console and paste the result here, for each of your environments. I think it is better to execute it after you run your pipeline. This will report all the packages used when running your code. Alternatively, use `packageVersion("flowCore")` and paste the result in both environments. Thanks.
Mike's link shows the code changed. Only inspect it.

**Comment by gfinak** [comment]
@Gesseca 
In order to install from github (rather than Bioconductor) you need to use the `devtools` package, and install via 
```
devtools::install_github("RGLab/flowCore", ref = "trunk")
```

Please, also include your `sessionInfo()` pasted in your response. (yes that is a command you type into your R console).
Finally, for the future, please read on how to write a good bug report. [Here's a link to some discussion on the rstudio site](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219)

- Include a description of the bug.
- Please don't paste monolithic text attachments of code, we will ignore them. 
- Try to make your examples minimal, self contained, and reproducible (so that we can copy-paste the code and reproduce your error).
- Include a description of the expected output and the observed output.
- Include a description of your system set up via `sessionInfo()`.

Finally, let us know when your bug is resolved so we  (or you) can close an issue.
Best

**Comment by Gesseca** [comment]
Ok, so it looks like the versions ARE different:

packageVersion("flowCore")
[1] ‘1.46.1’

packageVersion("flowCore")
[1] '1.44.2'

But as I literally just re-installed flowCore in both environments, I don't understand why they aren't the same, latest version. Does anyone know why that would be? I just used the code on the Bioconductor website: 

source("https://bioconductor.org/biocLite.R")
biocLite("flowCore")

**Comment by Gesseca** [comment]
Thanks, gfinak. This is my first GitHub post. I will follow the guidelines in the future. Actually I didn't know if this was a bug report or if I was doing something wrong..

**Comment by gfinak** [comment]
@Gesseca no worries. [this comment](https://github.com/RGLab/flowCore/issues/116#issuecomment-414704883) describes how to install from Github rather than BioConductor so that you get the version with  [Mike's](@mikejiang) lastest [patch](https://github.com/RGLab/flowCore/commit/e57d42948c759313554488aca144f8e77eeb2e3c).

**Comment by Gesseca** [comment]
Session info for the docker-PC environment:

R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4

Session info for the home environment in Rstudio:

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] FlowSOM_1.12.0  igraph_1.2.2    flowCore_1.46.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18                lattice_0.20-35             matrixStats_0.54.0          mvtnorm_1.0-8               XML_3.98-1.16              
 [6] corpcor_1.6.9               rrcov_1.4-4                 grid_3.5.1                  tsne_0.1-3                  magrittr_1.5               
[11] stats4_3.5.1                pcaPP_1.9-73                graph_1.58.0                robustbase_0.93-2           tools_3.5.1                
[16] Biobase_2.40.0              DEoptimR_1.0-8              parallel_3.5.1              compiler_3.5.1              ConsensusClusterPlus_1.44.0
[21] pkgconfig_2.0.2             BiocGenerics_0.26.0         cluster_2.0.7-1            

Thank you all very much for your help!

**Comment by Gesseca** [comment]
It looks like I also have different versions of R! No wonder things aren't working properly. Can I just download the latest versions of R on both? Now I"m not sure, since that didn't work for flowCore...

**Comment by gfinak** [comment]
The version of flowCore on your docker image is out of date, as is the version of R (3.5.1 is the latest). 
In order to update R on the docker environment you would need to rebuild the docker container after editing the `Docker` file. That's not an issue for here.

For now, suffice to say you *shouldn't use that docker image, it's out of date*. Find a way to get an updated image. 

I maintain a docker image with the flow cytometry tools [gfinak/opencyto](https://hub.docker.com/r/gfinak/opencyto/) but it is a bit dated at the moment, I will have to rebuild it, then notify you.

For your home system, you should install the development version of `flowCore` **from github**, [as described here](https://github.com/RGLab/flowCore/issues/116#issuecomment-414704883)

**Comment by Gesseca** [comment]
Ok, thank you @gfinak. I actually only started using the docker image to get around the problems in my home environment. I will not need it if I can get my code working properly. Do you see any issues with the session info from my home environment? I had a problem there with the write.FCS() command, which is why I switched to the docker image, but that created a new, different problem with write.FCS(). 

I assume I should post my home environment problem with write.FCS() in a different thread? Or can I continue the discussion here?

**Comment by gfinak** [comment]
Go ahead and start a new issue for your `write.FCS()` problem. I will close this issue and redirect there.
