### ISSUE TITLE
Exporting FCS files from gated data

### ISSUE THREAD

**Issue by CRStevens54** [RGLab/flowCore#141]
Hi All,

This is not a bug, but a question.

I am trying to split out populations from a flowset of FCS files, then I want to take the remaining gated population and make it into a flowframe so I can export the newly gated FCS files.  Is there a way to do this with FlowCORE?

Here is my code:

FCSfiles_pregate <- read.flowSet(path ="./Debarcoded",
                                 pattern='*.fcs',
                                 transformation=F)

##  Gates for specific populations ###
rectGate_beads <- rectangleGate("Ce140Di"=c(0, 1000), "Lu175Di"=c(0, 1000))
rectGate_livedead <- rectangleGate("Pt194Di"=c(0, 250), "Pt195Di"=c(0, 250))
rectGate_Singlets <- rectangleGate("Event_length"=c(0, 250), "Pt195Di"=c(0, 250))

##  applying gates to FCS files from original flowset ###
nobeads <- split(FCSfiles_pregate, rectGate_beads)

nobeads_livedead <- split(nobeads$`defaultRectangleGate+`, rectGate_livedead)

nobeads_livedead_Singlets <- split(nobeads_livedead$`defaultRectangleGate+`, rectGate_Singlets)

### want to produce FCS files for newly gated pop ###
write.FCS(nobeads_livedead_Singlets$`defaultRectangleGate+`, "./debarcoded/gated.fcs")

**Comment by mikejiang** [comment]
I would recommend you read section 5 of the [package vignette](https://bioconductor.org/packages/devel/bioc/vignettes/flowCore/inst/doc/HowTo-flowCore.pdf) which talks about `GatingSet` and 
>flowWorkspace and openCyto framework (http://opencyto.org)
offers much more versatile tools for such tasks though the GatingSet class. The general idea is to let the software handle the organization of intermediate results, and
operations and to provide a unified API to access and summarize these operations.

Since your workflow doesn't involve compensation and transformation, you can skip these parts and go directly to the sub-section of `5.4 Add the gates`. 
Once you have all the gates and gated pops well organized in `GatingSet`, you can easily query and extract the gated data from it through `getData` method.
check out the [flowWorkspace package](https://bioconductor.org/packages/release/bioc/html/flowWorkspace.html) for more details
