### ISSUE TITLE
read.FCS should gracefully handle duplicate channel names

### ISSUE THREAD

**Issue by cciccole** [RGLab/flowCore#161]
**Describe the Request**
Duplicate channel names are against spec and yet they happen quite often. This currently causes a specific error: `Multiple channels from one FCS are matched to the same alias!`.

**To Reproduce**
`read.FCS(...)` an FCS file with duplicate channel names.

**Expected behavior**
It would be nice if there were a setting that automatically dealt with duplicate channel names by renaming them to not be duplicate. For example, by appending `-N` to the duplicate names where N is an increasing integer.

**Comment by mikejiang** [comment]
The same issue was brought up not long ago #159 . Maybe it's worth to add the support?

**Comment by jacobpwagner** [comment]
It seems reasonably easy. As @cciccole mentioned, it should be easy to add a line in `update_channel_by_alias` to append an index after the duplicate channel name. I can try it out and see what the ramifications are.

**Comment by cciccole** [comment]
Thoughts on how to provide a param for this behavior? The default behavior should still be to fail since it's against FCS spec.

Either add a new param or deepen the functionality of the `channel_alias` argument to be able to trigger this behavior? E.g., by passing in a certain character argument instead of null or data.frame.

If a new param is added it will have to be added to the other similar functions such as for reading fcs header.

**Comment by SamGG** [comment]
I vote up, but with warning messages as this handling is not compliant with FCS standard.
FYI, as proposed by @cciccole, suffixing with `-N` the parameter name `$PnN` has been adopted by FlowJo (as tested in v10.5.3 with the file of #159 ), but the `$PnS` is unchanged.
Thanks.

**Comment by jacobpwagner** [comment]
Duplicate `$PnN` causes a bit of an issue for `$SPILLOVER`, though, right? Say we have two channels with `$PnN` of `FL-1`, then that introduces ambiguity with regard to which row/column of the spillover matrix corresponds to _which_ `FL-1` channel. By default we could assume the same ordering (which will probably cover most use cases), but even then if `$SPILLOVER` contains only a subset of the duplicated channels (say only one of two `FL-1`), then which are we to assign? The first? Generally the spillover matrices contain all channels, but the alternative is technically a sub-case that must be accounted for.

I can always add this default logic for how to handle `$SPILLOVER` so that it is read in successfully and add a line in the warning indicating that the user should clarify it by altering the column names (or at least verify their correctness) before attempting to apply it for compensation. Does that sound agreeable to everyone?

**Comment by SamGG** [comment]
Thanks for this deep investigation. Currently I never met the duplicated $PnN problem.
The examples in #159 sounds to be mass cytometry. So no spillover matrix by default and none in the given file. The faulty parameter called "treatment" has been added by the expert or some post-processing software. I don't think it directly result from the acquisition.
The flow cytometry files I usually encounter have a partial spillover matrix since FSC-x and SSC-x are not included in the matrix. In my experience, partial spillover is the generality.
**My opinion** I would keep the solution simple:
```
dup_spill <- duplicated $PnN in the spillover matrix
if (dup_spillover) then stop read.FCS
dup_param <- duplicated $PnN
if (dup_param) then
   if (dup_param in dup_spill) then stop read.FCS
   suffix dup_param
```
I think a duplication in the spillover matrix is very weird. But if you feel the patching code will not lead to border effects, it's OK.

**Comment by cciccole** [comment]
@jacobpwagner good catch on the edge case.

I agree with Samuel that it seems unlikely that the edge case will happen. Failing with an error is probably the safest operation in the case that it does happen.

**Comment by jacobpwagner** [comment]
In the spirit of allowing FCS files to be read in so that problems can be addressed in the R object, I decided to allow the case of a duplication in the spillover matrix with a warning rather than an error. I agree that it would be a weird edge case, but in the event that it occurs and causes issues in later analysis, the warning should make it obvious why.

**Comment by SamGG** [comment]
Good work!

``` r
# This failed before
df <- data.frame(channels = c("FL1,FL2", "FL3,FL4"), alias = c("CD4", "CD8"))
alias_env <- flowCore:::check_channel_alias(df)
ls(alias_env)
#> [1] "FL1" "FL2" "FL3" "FL4"

update_channel_by_alias(paste0("FL", c(1:4)), alias_env)
#>   orig_channel_name new_channel_name
#> 1               FL1            CD4-1
#> 2               FL2            CD4-2
#> 3               FL3            CD8-1
#> 4               FL4            CD8-2
#> Warning in update_channel_by_alias(paste0("FL", c(1:4)), alias_env): channel_alias: Multiple channels from one FCS are matched to the same alias!
#>                  Integer suffixes added to disambiguate channels.
#>                  It is also recommended to verify correct mapping of spillover matrix columns.
#> [1] "CD4-1" "CD4-2" "CD8-1" "CD8-2"

# Still OK
update_channel_by_alias(paste0("FL", c(1:4, 4)), alias_env)
#>   orig_channel_name new_channel_name
#> 1               FL1            CD4-1
#> 2               FL2            CD4-2
#> 3               FL3            CD8-1
#> 4               FL4            CD8-2
#> 5               FL4            CD8-3
#> Warning in update_channel_by_alias(paste0("FL", c(1:4, 4)), alias_env): channel_alias: Multiple channels from one FCS are matched to the same alias!
#>                  Integer suffixes added to disambiguate channels.
#>                  It is also recommended to verify correct mapping of spillover matrix columns.
#> [1] "CD4-1" "CD4-2" "CD8-1" "CD8-2" "CD8-3"

# Unaliased channels are suffixed
update_channel_by_alias(paste0("FL", c(1, 3, 5, 5)), alias_env)
#>   orig_channel_name new_channel_name
#> 1               FL5            FL5-1
#> 2               FL5            FL5-2
#> Warning in update_channel_by_alias(paste0("FL", c(1, 3, 5, 5)), alias_env): channel_alias: Multiple channels from one FCS are matched to the same alias!
#>                  Integer suffixes added to disambiguate channels.
#>                  It is also recommended to verify correct mapping of spillover matrix columns.
#> [1] "CD4"   "CD8"   "FL5-1" "FL5-2"
```

**Comment by SamGG** [comment]
Comment: channel_alias data frame columns checking

https://github.com/RGLab/flowCore/blob/6dd1a0b782dc518e25344fdb3865aca02d01443b/R/IO.R#L886-L887

The error message does not match the test as setequal requires that the two sets are EXACTLY identical.

I think testing the length of setdiff would suffice and match the error message.

``` r
setdiff(c("alias", "channels"), c("alias", "channels", "toto"))
#> character(0)
setdiff(c("alias", "channels"), c("alias", "toto"))
#> [1] "channels"
setdiff(c("alias", "channels"), c("channels", "toto"))
#> [1] "alias"
```

**Comment by jacobpwagner** [comment]
This has gotten a little outside of the scope of the original issue, but I'll address these here. In the first case, the partial matching logic is inverted from how you are viewing it. Ideally, the `channel` column would uniquely specify channels to be renamed to their corresponding `alias`. However, in the absence of that, _each of the original channel names_ will be checked for partial match _against the keys_ (`channel` column in `channel_alias`). Taking your first example:
```
df <- data.frame(channels = c("FL2", "FL3,FL4", "FL11"), alias = c("CD4", "CD8", "CD45"))
alias_env <- flowCore:::check_channel_alias(df)
ls(alias_env)
#> [1] "FL11" "FL2"  "FL3"  "FL4"

update_channel_by_alias(paste0("FL", c(1, 11)), alias_env)
#> [1] "FL1"  "CD45"

# FL1 is not a partial match of FL11?
```
When it gets to `FL1`, it looks for a channel in `df` that will partially match to `FL1` (the value in the `channel` column is the regex and the original channel name is the string to match). This logic enables you to put things like `CD45` in the channel column of `channel_alias` and match to `CD45RA` in the original channel names for example. But anyway, no channel in `df` partially matches to `FL1`, because as you correctly point out, `FL11` should not partially match to `FL1`. Basically, you just have the regex logic flipped I think.

Your second example is just the flip side of that.

**Comment by jacobpwagner** [comment]
And to your second point @SamGG, yeah, technically a `setdiff` length check would allow more flexibility and fit the error message better. Do you think it's likely that users would need to append extra columns to `channel_alias`? It's basically meant to just be a two-column simple map and I don't want users thinking extra columns have any bearing. So I may just change the error message to "channel_alias must contain 'alias' and 'channels' columns (and only those)" or something, if that seems less confusing.

Feel free to reply here or open a new issue, but I'm going to go ahead and close this issue based on the original request.

**Comment by SamGG** [comment]
Concerning the clipping, I would have started the message with "\n".
