### ISSUE TITLE
print warning messages when 'truncate_max_range' happens in read.FCS

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#169]
The default `truncate_max_range` behavior could sometime cause confusions when `FCS` file doesn't have `$PnR` value set properly, which could happen especially the fcs files are handcrafted by user scripts. (also see #109 ).
For example, `as_flowFrame` function provided by `premessa` package (https://github.com/ParkerICI/premessa) somehow sets the range for `integer` value inaccurately. i.e. `61292` (actually data) --> `61291` (`PnR`) when it constructs a `data.frame` into `flowFrame`. 
This causes the data to be truncated during `read.FCS` following `write.FCS` operation.

When users noticed the issue with data, typically the first impression is something is wrong with `write.FCS`. And the second suspect will be `read.FCS`. And the real culprit of `$PnR` aspect of the `flowFrame` during its construction process is usually ignored.

To ease the troubleshooting process in future (for both users and `flowCore` developer), we may want to print some warning messages when 'truncate_max_range' does occur in `read.FCS`.

**Comment by mikejiang** [comment]
```r
> mat <- matrix(1:100, ncol = 1, dimnames = list(NULL, "APC-A"))
> fr <- flowFrame(mat)
> keyword(fr)[["$P1R"]] <- 99 ##mimic the effect of `premessa::as_flowFrame`
> range(fr1, "data")
    APC-A
min     1
max    99
> 
> tmp <- tempfile()
> write.FCS(fr, tmp)
[1] "/tmp/Rtmp6bD5Hw/file6cc5668fa8a3"
> 
> fr1 <- read.FCS(tmp)
Warning message:
In readFCSdata(con, offsets, txt, transformation, which.lines, scale,  :
  some data of 'APC-A' channel exceeds its $PnR value and will be truncated to : 99
 Either fix $PnR in FCS or set 'truncate_max_range = FALSE'
> range(fr1, "data")
    APC-A
min     1
max    99
```

**Comment by SamGG** [comment]
Your changes also alert when the data are below the min limit.
Thanks.

**Comment by mikejiang** [comment]
`min.limit` truncation doesn't occur unless it is explicitly turned on by user

**Comment by SamGG** [comment]
Correct. I always get confused by the default value of readFCSdata being -111.

**Comment by lchan8** [comment]
Hello,

I came across this when I was doing premessa paneleditor_GUI() and got lots of warning messages with "truncate_max_range." Do you have advice on how I can fix $PnR values? @mikejiang @SamGG 

I did manual gating in FlowJo of the live intact cells before exporting these FCS files. I noticed that I only got the "truncate_max_range" warning messages in the post-export files and not in the pre-export files.

**Comment by SamGG** [comment]
My point targeted channels where the values (aka intensities) were integers. So, if the channels involved in your issue are not integers, this is another. And it still better to open a new issue rather than posting to an old issue. I encourage you to open a issue in which you give the version of flowCore package.
IIUC, it sounds to be an effect of FlowJo. If you reopen a "faulty" FCS, you should find an alert such "events are stacked on the axis" for at least one channel.
With R and no truncation, you could also look at the range (min and max) of every channel before and after gating in order to identify "faulty" channels. See Jake's answer and range use https://support.bioconductor.org/p/130629/
IMO, the best would be to modify Premessa in order to append `truncate_max_range = FALSE`. I noticed 10 to 15 calls to read.FCS).
Best.
