### ISSUE TITLE
Compensation parameter %name not found in cytoframe parameters

### ISSUE THREAD

**Issue by netphar** [RGLab/flowCore#174]
Hi,

this is not an issue, but a question. I tried grokking the manuals, but to no avail so far.

Setup: I have an FCS file and a corresponding FlowJo workspace with gates applied. 
```
map <- data.frame(alias = c("BL1-H"), channels = c("FJComp-BL1-H")) # check if setting channel alias would work
x <- read.FCS(fcs, transformation = F, truncate_max_range = F, channel_alias = map)
flowjo_to_gatingset(ws, 
                    name=1, 
                    path='/Users/zagidull/Desktop/Bulat_A02_komal_FlowJo_vs_Intellicyte/13_02_2020/', 
                    subset = "IntelliCyt_iQue3.fcs"
                    ) # needed to change the name, removing the prepended string "export_"
Error in (function (ws, group_id, subset, execute, path, h5_dir, includeGates,  : 
  compensation parameter 'BL1-H' not found in cytoframe parameters!
```
The error makes sense, because channel names that I have in the FCS file are as follows (output truncated):
```
> summary(x)
FSC-A      FSC-H      SSC-A      SSC-H        BL1-H FJComp-BL2-H FJComp-BL4-H FJComp-RL1-H  FJComp-VL1-H  FJComp-VL4-H  FJComp-VL6-H     Time
```
All the laser channels have a string prepended "FJComp-...". I can change their names using the custom `map` dataframe. However, i am not using the already read FCS file (denoted with x) when applying `flowjo_to_gatingset()` func, since it reads the FCS file from the disk. 

I was thinking that I could re-write the FCS file on disk after I modified their channel names with `channel_alias` parameter. Or maybe I could supply an already read into R FCS file to the `flowjo_to_gatingset()` - that i did not figure out yet. However, I have a feeling there must be a better way.  

thanks for any help!

**Comment by mikejiang** [comment]
`flowjo_to_gatingset` currently doesn't take the `cytoset` as alternative input yet, which leaves you `write.FCS` as the only option. But you want to figure out why the FCS files you are feeding to ``flowjo_to_gatingset` call are different from the original version that was used by flowJo (which doesn't have prefix `FJComp-`. It is important to use the same files otherwise the results can't be guaranteed to be correct even if you manage to restore the channel names.

**Comment by netphar** [comment]
@mikejiang I know for sure that this is a correct fcs and a correct flowjo workspace - i saw it being gated right in front of me. 

I am basically stuck on `flowjo_to_gatingset` part. I did what you suggested, ie created a new fcs file using `channel_alias=` argument and `write.FCS`. So, I don't get the `compensation parameter not found in cytoframe` error, yay! Not so yay is that I m getting a new error:
```
> flowjo_to_gatingset(ws, 
+                     name=1, 
+                     path='/Users/zagidull/Desktop/Bulat_A02_komal_FlowJo_vs_Intellicyte/13_02_2020/', 
+                     subset = "IntelliCyt_iQue3.fcs"
+                     ) # needed to change the name, removing the prepended string "export_"
Error in (function (ws, group_id, subset, execute, path, h5_dir, includeGates,  : 
  colname not found: BL2-H
```
how can i access the colnames that should be found vs the ones that are actually found? 

in case it is easier to see the actual files, I uploaded the files on the dropbox. There are three files: the original one (export_IntelliCyt_iQue3.fcs), the one where I modified the channel names as per your suggestion (IntelliCyt_iQue3.fcs) and the flowjo workspace, where the gating was done (13.02.2020.wsp) https://www.dropbox.com/sh/xixo9jzrzwb4uwc/AADj9vTeZmy7N31BVmCStwXra?dl=0 

here is the code i am using:
```
require('flowCore')
require('flowWorkspaceData')
require('CytoML')
require('ggcyto')

setwd('/Users/zagidull/Desktop/Bulat_A02_komal_FlowJo_vs_Intellicyte/13_02_2020/')
fcs <- '/Users/zagidull/Desktop/Bulat_A02_komal_FlowJo_vs_Intellicyte/13_02_2020/export_IntelliCyt_iQue3.fcs'
wsp <- '/Users/zagidull/Desktop/Bulat_A02_komal_FlowJo_vs_Intellicyte/13_02_2020/13.02.2020.wsp'
path <- '/Users/zagidull/Desktop/Bulat_A02_komal_FlowJo_vs_Intellicyte/13_02_2020/'
newname <- 'IntelliCyt_iQue3.fcs'

# creating a map
x <- read.FCS(fcs, transformation = F, truncate_max_range = F) #, channel_alias = map)
channels = colnames(x)      
alias = c("FSC-A","FSC-H","SSC-A","SSC-H","BL1-H","BL2-H","BL4-H","RL1-H","VL1-H","VL4-H","VL6-H","Time") 

# read anew
if (length(alias) == length(channels)){
  map <- data.frame(alias, channels) # check if setting channel alias would work
  x <- read.FCS(fcs, transformation = F, truncate_max_range = F, channel_alias = map)
  write.FCS(x, newname)
  }
  

ws <- open_flowjo_xml(wsp) # from CytoML package
fj_ws_get_samples(ws, group_id = 1) # gets samples

flowjo_to_gatingset(ws, 
                    name=1, 
                    path='/Users/zagidull/Desktop/Bulat_A02_komal_FlowJo_vs_Intellicyte/13_02_2020/', 
                    subset = newname
                    ) # needed to change the name, removing the prepended string "export_"
```

**Comment by mikejiang** [comment]
First of all, you should use the original raw FCS (i.e.  generated from the instrument, NOT the exported one by flowjo), because `export_IntelliCyt_iQue3`  could have already been compensated (based on the fact of prefix `FJComp-` prepended to the channel names). When you simply restore the colnames, it doesn't restore the data, which may lead to compensate it twice when your call `flowjo_to_gatingset`.

Secondly,  here is the `compensation` info stored in wsp file
```xml
<transforms:spilloverMatrix prefix="Comp-"   suffix="" >
         <data-type:parameters>
           <data-type:parameter data-type:name="BL1-H" />
           <data-type:parameter data-type:name="BL2-H" />
           <data-type:parameter data-type:name="BL4-H" />
           <data-type:parameter data-type:name="RL1-H" />
           <data-type:parameter data-type:name="VL1-H" />
           <data-type:parameter data-type:name="VL4-H" />
           <data-type:parameter data-type:name="VL6-H" />
         </data-type:parameters>
``` 
Apparently `BL2-H` is supposed to be compensated and thus will be prefixed `Comp-` thus only `Comp-BL2-H` will be visible afterwards, but here is the gate defined in wsp
![image](https://user-images.githubusercontent.com/1385649/74969245-0c6d9580-53d1-11ea-8060-aab6eebec777.png)

which still refers to `BL2-H`.
I don't know how this happened in the first place because I can't reproduce the same behavior in flowJo (i.e. two versions of  the same channel : raw vs compensated , are both present in one workspace)

You can manually correct the wsp file (i.e. add `Comp-` back to `BL2-H`) to proceed `flowjo_to_gatingset`. But again, both FCS and wsp files seem to be problematic, it is better to get the correct data instead of doing all these hacks.

**Comment by netphar** [comment]
thank you. I will get back to the source and get the correct data. Manually hacking and slashing feels very wrong indeed
