### ISSUE TITLE
corrupted fcs file keyword $TOT does not match number of cells

### ISSUE THREAD

**Issue by janinemelsen** [RGLab/flowCore#179]
Hi guys,

I have a corrupted fcs file which I am trying to repair. When trying to read the FCS in R I get the following error:

Error in read.FCS("P:/kjc/FACS-LSR/Monique Kaluza/FCS 3.0/20201501_temp/ad5a6ae0-c734-408a-a9b2-0a5c1c23cf07.fcs",  : 
  fileP:/kjc/FACS-LSR/Monique Kaluza/FCS 3.0/20201501_temp/ad5a6ae0-c734-408a-a9b2-0a5c1c23cf07.fcsseems to be corrupted. 
 The actual number of cells in data section (1048575) is not consistent with keyword '$TOT' (1000000000)

The problem is that the file contains a lot of zero's and the number of actual cells (1048575) does not match the $TOT keyword.

Is there a way in which I can adjust the TOT keyword or let the read.FCS function ignore this discrepancy?

Best,

Janine

**Comment by mikejiang** [comment]
You can use `which.lines = 1:1048575` to tell the parser only read a specific number cells to bypass this validity check. But since the data is corrupted, I recommend to to get the correct version of the FCS instead of hack around (by doing so, you are at risk of getting wrong data results, because corrupted data is corrupted!)

**Comment by janinemelsen** [comment]
Thanks, it worked!
