### ISSUE TITLE
Removing scatter parameters from flowSet

### ISSUE THREAD

**Issue by browshanravan** [RGLab/flowCore#184]
I am trying to remove non-fluorescent channels such as ```FSC-A```, ``` time``` and etc from my flowSet. Is there a function in ```flowCore``` or an R command that would allow me to do this? 

I have posted this question on [stack overflow](https://stackoverflow.com/questions/61220161/removing-s4-class-column-in-r-flowcore) but no luck so far. Any suggestions?

**Comment by gfinak** [comment]
First: Why?
Second: just subset the columns you want to keep

**Comment by jacobpwagner** [comment]
`GvHD[[1]]` is a `flowFrame`, not a simple data frame, which is why the NULL assignment from that stack overflow post doesn't work. The underlying representation is also a matrix, which also doesn't support dropping a column by assigning it `NULL`.

If you want to drop columns, here are some ways you could do that. Note for all of these I'm subsetting columns for the whole `flowSet` rather than looping through each `flowFrame`. But you could perform these operations on each `flowFrame` as well.

As Greg mentioned, choose the columns you want to keep:
```
data(GvHD)
all_cols <- colnames(GvHD)
keep_cols <- all_cols[!(all_cols %in% c("FSC-H", "SSC-H"))]
GvHD[,keep_cols]
```
Or you could just filter in the subset:
```
GvHD[,!colnames(GvHD) %in% c("FSC-H", "SSC-H")]
```
You could also grab the numerical indices you want to drop and then use negative subsetting.
```
# drop_idx <- c(1,2)
drop_idx <- which(colnames(GvHD) %in% c("FSC-H", "SSC-H"))
GvHD[,-drop_idx]
```

However, I also second Greg's first point. Why do you need to drop the scatter parameters?

**Comment by browshanravan** [comment]
Thank you so much @jacobpwagner it works! I will post your solution on [stack overflow](https://stackoverflow.com/questions/61220161/removing-s4-class-column-in-r-flowcore) and credit you with the solution. Thank you one again.

@gfinak & @jacobpwagner I was hoping to use my flowSet for t-SNE plots and as far as I understand it if the data has linear parameters, such as time or FSC-A, they will distort the plots but I could be easily wrong.

**Comment by SamGG** [comment]
Hi,
Just select the markers you want to send to tSNE in the same way you have done.
Some populations could be found using FSC and SSC, but these channels require adapted transformation and scaling. If you begin with R, you chose the more robust way by ignoring them first.
Best.

**Comment by browshanravan** [comment]
Many thanks @jacobpwagner @gfinak @SamGG  for taking the time and answering my questions.
