### ISSUE TITLE
Weird FS00-A and SS02-A values in YETI analyzer

### ISSUE THREAD

**Issue by dtelad11** [RGLab/flowCore#210]
**Describe the bug**
I have an FCS file from a YETI analyzer. When looking at FCS versus SSC, I am seeing different values between FlowJo and FlowCore.

FlowJo:

![image](https://user-images.githubusercontent.com/7569462/109014325-07958e80-7682-11eb-8895-c978ac5f5f00.png)

FlowCore:

![image](https://user-images.githubusercontent.com/7569462/109014386-154b1400-7682-11eb-8922-65a5ee7220c2.png)

The FSC_A values in FlowCore go from 94,124,032 to 2,147,483,392. In FlowJo, they go from 0 to 214,748, which is the $PnR for this channel. I had to import the file with the `truncate_max_range = FALSE` flag.

**To Reproduce**
Reproducing the bug requires a specific FCS file, I'm happy to share it over email.

**Expected behavior**
FSC_A values should be between 0 and 214,748, not between 94m and 2.2b.

**sessionInfo():**
```

R version 4.0.3 (2020-10-10) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 16.04.7 LTS  Matrix products: default BLAS:   /usr/lib/libblas/libblas.so.3.6.0 LAPACK: /usr/lib/lapack/liblapack.so.3.6.0  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8         [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] ggplot2_3.3.3  loaded via a namespace (and not attached):  [1] Rcpp_1.0.6          plyr_1.8.6          pillar_1.4.7        compiler_4.0.3      cytolib_2.2.0        [6] viridis_0.5.1       tools_4.0.3         digest_0.6.27       lifecycle_1.0.0     tibble_3.0.6        [11] gtable_0.3.0        viridisLite_0.3.0   pkgconfig_2.0.3     rlang_0.4.10        cli_2.3.0           [16] orloj_0.1.0         patchwork_1.0.1     ggrepel_0.9.1       parallel_4.0.3      gridExtra_2.3       [21] withr_2.4.1         dplyr_1.0.4         generics_0.1.0      vctrs_0.3.6         S4Vectors_0.28.0    [26] stats4_4.0.3        grid_4.0.3          tidyselect_1.1.0    glue_1.4.2          Biobase_2.50.0      [31] R6_2.5.0            pbapply_1.4-3       farver_2.0.3        purrr_0.3.4         RProtoBufLib_2.2.0  [36] magrittr_2.0.1      MASS_7.3-53         ggridges_0.5.3      matrixStats_0.57.0  scales_1.1.1        [41] ellipsis_0.3.1      BiocGenerics_0.36.0 assertthat_0.2.1    colorspace_2.0-0    flowCore_2.2.0      [46] labeling_0.4.2      RcppParallel_5.0.2  munsell_0.5.0       crayon_1.4.1
--
```

**Comment by SamGG** [comment]
Hi,
Outliers are shown on the right border of the FJ figure.
Did you try to expand the maximum value on Y axis?
Not an official answer.

**Comment by mikejiang** [comment]
why the x,y dimension names are different between the two?Any example file to share?

**Comment by dtelad11** [comment]
Thanks Samuel! I'm afraid the outliers don't explain the difference in the dynamic range of FSC/SSC.

Mike, I renamed them in R (that's part of my standard script for plotting data). Can I email you a file at your scharp.org email address?

**Comment by mikejiang** [comment]
to mike@ozette.ai

**Comment by SamGG** [comment]
@dtelad11 I thought you were concerned by the outliers missing at the top of the plot, which is the most important point for me. The scaling has something to do with the parameters in the header such as the exponent. Send me a link to retrieve your FCS if you wish.

**Comment by dtelad11** [comment]
@SamGG why would the exponent matter? There shouldn't be any transformation here (FSC is linear).

**Comment by SamGG** [comment]
Correct: `When linear amplification is used or when amplification is undefined such as with some calculated parameters, f1 and f2 are set to 0.`
But I would consider all the followings:
```
$DATATYPE Type of data in DATA segment (ASCII, integer, floating point).
$PnB Number of bits reserved for parameter number n.
$PnE Amplification type for parameter n.
$PnG Amplifier gain used for acquisition of parameter n.
$PnR Range for parameter number n.
```
You showed 2 views, but does Yeti have its own display?

> To make a decision, you have to be an odd number of people, and three is already too many.
> Georges Clemenceau

**Comment by mikejiang** [comment]
flowCore reads whatever was recorded in FCS file,  I don't have access to flowjo at the moment so I am not sure which part of the fcs file triggers flowjo to rescale the data to its instrument range.

**Comment by jspidlen** [comment]
What’s the $PnG for the forward and side scatters? Can you share the FCS file? It seems as if flowCore multiplies the scatter values by $PnG, which gets you those large values. Recently, several instrument vendors started showing large values for both scatter and fluorescence channel. According to David Parks, this is mostly a marketing trick since those instruments have nowhere close to the resolution that these large ranges are suggesting. It shouldn’t really matter for manual analysis, but it can screw up some automated methods that were developed with ranges of ~10^5 in mind and are now applied to data that appears as 10^9.

**Comment by mikejiang** [comment]
```
$P1B|32|$P1R|214748|$P1N|FS00-A|$P1S|FSC 488_10-A|$P1G|1|$P1E|0,0
```

**Comment by jspidlen** [comment]
Thanks Mike,
El-ad just shared the FCS file with me as well, looking at it now, and you are correct, it’s not the $PnG issue in this case. So, looking at FlowJo’s source codes, we do the rescaling because we recognize that this is a YETI. FlowJo recognized 30+ instruments and over the years, we have worked with a ton of customers as well as all the instrument vendors to figure out how to rescale the parameters, when to use linear vs. log vs. biex scale, how to parameterize those scales by default, etc. It’s not ideal but it’s been our approach to address the problem of instrument vendors storing data in some of these rather random ranges. (and going way over of what they specify in $PnR). The scatters from a YETI are rescaled in FlowJo to avoid values greater then 214748.

**Comment by mikejiang** [comment]
@jspidlen Thank you for quick and thorough explanations! I will discuss with @gfinak to see what will be our strategy here.

**Comment by dtelad11** [comment]
Thanks @jspidlen and @mikejiang!

**Comment by dtelad11** [comment]
To recap: The YETI instrument has some weird numbers in the FCS files. For example, forward/side scatter are five orders of magnitude too big. The antibody channel values are also unusual, I'm trying to figure them out now.

Either way, flowCore is doing everything right -- this is the vendor's fault for ignoring the standard. Thanks everyone for helping.

**Comment by SamGG** [comment]
4 orders of magnitude.

**Comment by dtelad11** [comment]
Oops, yes, four orders of magnitude. The fifth order is my agitation ;)
