### ISSUE TITLE
HowTo? fr_append_cols on a cytoframe?

### ISSUE THREAD

**Issue by malcook** [RGLab/flowCore#228]
I find that if I use `cytoframe_to_flowFrame` I can use ` fr_append_cols` to add a new column the result, but trying to do so fails on the cytoframe with this error

```
Error: parameter names don't match colnames of the exprs matrix
In addition: Warning message:
In colnames(exprs(object)) == value$name :
  longer object length is not a multiple of shorter object length
```

I wonder if there is a way to do this, and more specifically, to do it to all `cytoframes` in a `cytoset`.

My application is a create a derived column which is the ratio of two others, which I can then plot and gate on.

**Comment by jacobpwagner** [comment]
I think you're looking for [`cf_append_cols`](https://github.com/RGLab/flowWorkspace/blob/28cc922acfdf5e4a4e70996609ceee205a817ca0/R/cytoframe.R#L1149-L1155). 

You can loop over the `cytoframes` and add whatever column (after putting it in a matrix with column names). Note that it's not necessary to assign the augmented `cytoframe`s back into the `cytoset` here because they are reference objects  (as opposed to `flowFrame`s).

```
library(flowCore)
library(flowWorkspace)
data(GvHD)

cs <- flowSet_to_cytoset(GvHD)

lapply(cs, function(cf){
  dummy_col <- matrix(sample(c(0,1), size = nrow(cf), replace = TRUE))
  colnames(dummy_col) <- "dummy"
  cf_append_cols(cf, dummy_col)
})
```

**Comment by malcook** [comment]
Aha, my oversight, thank you @jacobpwagner !
