### ISSUE TITLE
Giving a bad list of channels to Transform fails to produce a warning.

### ISSUE THREAD

**Issue by jfrelinger** [RGLab/flowCore#26]
```
> m
[1] "FSC-H"          "SSC-H"          "CD19 FITC"      "CD38 PE"       
[5] "CD3/CD20 PerCP" "FL1-A"          "CD27 APC"      
> colnames(fs)
[1] "FSC-H"          "SSC-H"          "CD19 FITC"      "CD38 PE"       
[5] "CD3/CD20 PerCP" "CD27 APC"    

> # note FL1-A is not in colnames(fs)

> max(exprs(fs[[1]])[,'CD19 FITC'])
[1] 9646.616

> lgcl <- logTransform()
> logicle_transform <- transformList(m[3:length(m)], lgcl)
> fs <- transform(fs,logicle_transform)
copying data slice:FC 001 Day7.fcs
write FC 001 Day7.fcs to empty cdf slot...
```
<snip> no warnings generated..
```
> max(exprs(fs[[1]])[,'CD19 FITC'])
[1] 9646.616
```
if I remove 'FL1-A' form m it works.
```
> max(exprs(fs[[1]])[,'CD19 FITC'])
[1] 3.984375
```

**Comment by mikejiang** [comment]
Turns out the evil still originates from this ugly  `method dispatching` described [here](https://github.com/RGLab/flowCore/blob/master/R/flowFrame-accessors.R#L423-L425)
Basically it was trying to simply `transform` API by manually handling two different `formals` in the same interface. And it is in fact far from being robust regardless of the patch we added last time.

**Comment by mikejiang** [comment]
@gfinak and I came up a more robust(hopefully) yet informative dispatching strategy. 
There are two forms of `transform` call:
A) transform(fs, `FSC-H`=asinhTrans(`FSC-H`), ...)
B) transform(fs, translist)

Dispatch will be based on whether the `arguments` (except the first one) are named explicitly during the call .
e.g.  `A` form
```r
> transform(fr, `(Ir191)Dd` = sin(`(Ir191)Dd`))
flowFrame object '1.fcs'
with 296656 cells and 2 observables:
          name     desc range   minRange      maxRange
$P46 (Ir191)Dd      DNA 24761 -0.9147058    -0.8949402
```
and  `B` form.  Due to the correct dispatch, now it throws the very error message we need to see
```r
> transform(fr, transList)
Error in y@f(x[, y@input]) : 
  Logicle Exception: IllegalParameter: W is not positive 
```

If user wants `A` but forget to give the `argument name`, we will still be able to give a intuitive error.
```
> transform(fr, sin(`(Ir191)Dd`))
Error in transform(fr, sin(`(Ir191)Dd`)) : 
  the unnamed argument must be a 'transformList'!
```

**Comment by mikejiang** [comment]
Actually this `non-standard evaluation` approach still breaks in some scenarios due to the fact that `eval()` only evaluate the `expression` in `parent.frame()` (or specified enclosure) of the `transform` method. 
It is similarly described [here](https://github.com/RGLab/ncdfFlow/issues/31).
e.g. This will work
```r
f1 <- function(fr){
  transList <- transformList('FL1-H', log)
  transform(fr, transList)  
}
f1(fr)
```
Because  `transList` is defined in the `parent environment` of `transform` call.

But this will fail
```r
f1 <- function(fr){
  transList <- transformList('FL1-H', log)
  f2(fr,transList)  
}
f2 <- function(fr, ...){
  transform(fr, ...)
}
 f1(fr)
```
Because `transList` is not in the direct parent frame
```r
Browse[1]> eval(arg)
Error in eval(expr, envir, enclos) : object 'transList' not found
```
but the one further above.
```r
Browse[1]> eval(arg, parent.frame(2))
An object of class "transformList"
```
And there is really no good way to know at which level the `variable` referred by `...`  is defined especially in the programmatic context. So maybe we are gonna have to 
* either separate these two `forms` of transformation into two different APIs. 
* or simply deprecate the usage of `form A` (since it is not intended for programmatic purpose anyway  as mentioned in #24) 
@gfinak , thoughts?

**Comment by gfinak** [comment]
Yeah deprecate it.

Greg Finak

**Comment by mikejiang** [comment]
I found another workaround: add an argument `translist` to capture `transformList` and leave `...` to handle `form A` exclusively.  
```r
 definition=function(`_data`, translist, ...)
```
By this, we avoid any `non-standard evaluation` in `form B` so that it can be used in any context.
Now the same code above works.
```r
> f1 <- function(fr){
+   transList <- transformList('FL1-H', log)
+   f2(fr,transList)  
+ }
> f2 <- function(fr, ...){
+   transform(fr, ...)
+ }
> f1(fr)
flowFrame object '060909.001'
with 10000 cells and 7 observables:
     name       desc range minRange    maxRange
$P1 FSC-H FSC-Height  1024        0  1023.00000
$P2 SSC-H SSC-Height  1024        0  1023.00000
$P3 FL1-H       <NA>  1024        0     9.21034
```
