### ISSUE TITLE
Allow reading FCS files with diverse bitwidth

### ISSUE THREAD

**Issue by migaspar** [RGLab/flowCore#46]
As discussed [here](https://support.bioconductor.org/p/71235/) at least Partec CyFlow Cube 6 produces FCS files with diverse bitwidths (4 x 16 for FSC/SSC and FLx, 32 for TIME and 8 for DOUBLET). Currently flowCore does not support this. It is desirable that it is at least possible to read channels with identical bitwidths using column.pattern.

**Comment by mikejiang** [comment]
@jspidlen , I don't see the FSC standard explicitly describes this issue and would like to have your opinion about it.

**Comment by jspidlen** [comment]
If data type is float or double, then the bit width is fixed for all
parameters to 32 or 64, respectively. But if data type is integer then
different bit width is legal as far as the specification goes. This is why
there are different keywords for different parameters rather than a single
"$BITWIDTH" keyword. Having said that, this is the first time I have heart
that somebody is actually using it. In my opinion, this flexibility is
unnecessary and only complicates things for FCS consumers (implementors
trying to read FCS), but it is the way it was originally designed back in
1984 when space was much more expensive than it is now. Legacy is very
strong here and there are no plans of changing this particular aspect.

**Comment by mikejiang** [comment]
Thanks for the details, Josef! I will see what I can do about it. @migaspar , it would be helpful if you can send me your example FCS for testing.

**Comment by migaspar** [comment]
Sorry for the delay! I sent an email but obviously it arrived nowhere. 
First off, thanks for having a look at this issue. However, i still can't load the files (with and w/o column.pattern):

Can't determine value for 'signed' parameter because not all parameters
are of size 1 or 2!

I attached a small example file (renamed to .txt because of the upload policy here)
[example.fcs.txt](https://github.com/RGLab/flowCore/files/47371/example.fcs.txt)

**Comment by SamGG** [comment]
IO.R line 655-661: signed could become a vector for use at line 711?

**Comment by mikejiang** [comment]
@migaspar. It should read your file now. Let me know if it the data looks good.

**Comment by migaspar** [comment]
it does. thanks!
