### ISSUE TITLE
FlowJo exported file cannot be loaded with flowCore

### ISSUE THREAD

**Issue by dtelad11** [RGLab/flowCore#53]
I am getting the following when trying to import an FCS file that was exported by FlowJo:

```
> fcs_data <- flowCore::read.FCS(filename, transformation = FALSE)
Error in readFCSgetPar(x, paste("$P", 1:nrpar, "R", sep = "")) : 
  Parameter(s) $P38R not contained in 'x'
```

I saw that similar issues has been reported in the past, so it looks like FlowJo did not address this. I emailed them in parallel, but is it possible to "hack" a solution through flowCore in the meanwhile?

Thank you!

**Comment by mikejiang** [comment]
@jspidlen , Another bad export from `flowJo`? Is this something `flowRepository` also tolerate? If so, How do you handle the missing `$PnR`?(I thought this keyword is crucial for parsing FCS based on the standard).

**Comment by dtelad11** [comment]
Thank you for looking into this so quickly. I could share the file if necessary.

**Comment by mikejiang** [comment]
@dtelad11 ,yes, please.

**Comment by dtelad11** [comment]
File can be found here:

https://drive.google.com/open?id=0BxVdfdIC3IVodEVFUXdYblNzb0k

```
> flowCore::read.FCS("mikejiang_faulty_fcs_file.fcs")
Error in readFCSgetPar(x, paste("$P", 1:nrpar, "R", sep = "")) : 
  Parameter(s) $P38R not contained in 'x'
```

**Comment by jspidlen** [comment]
This is badly corrupted, I haven't seen such a thing before. The file says
there should be 38 parameters, but all the $P38... keywords are missing
(not just $P38R). Mike, FlowRepository cannot handle this either. I'd
suggest submitting this to FlowJo so that they can fix their software in
the first place. Or if you wanted, I could try talking to them on your
behalf; I occasionally work with FlowJo developers on issues like that, for
example, FlowJo used to put $PnR/0/ for the Time channel in their exported
files and this has just been fixed in FlowJo 10.1r7, which should be
released very soon. But it would be good to know more details on how
exactly the file was created, what version of FlowJo was used, etc.

Josef

**Comment by dtelad11** [comment]
@jspidlen @mikejiang First of all, thanks the two of you for the super-prompt reply. The files (there are actually a bunch of them) were generated by a tech in our lab. We're going to try and figure out which series of events lead to this specific corruption and then email FlowJo.

I guess that this can be closed, as it has nothing to do with flowCore.

Thanks again and happy holidays!

**Comment by mikejiang** [comment]
@jspidlen , Thanks for the confirmation. Yeah, go ahead to forward this issue to flowJo.
