### ISSUE TITLE
Trouble adapting openCyto Transformation

### ISSUE THREAD

**Issue by kratschie** [RGLab/flowCore#72]
Hello,

being still pretty new to OpenCyto I have been working through the bioconductor Tutorial and am now trying to reproduce the data output and plots with our data. I get an error trying to do the transformation part:

######################
# Transformation
chnls <- parameters(m_compMat)
transFuncts <- estimateLogicle(ncfs[[1]], channels = chnls)
ncfs_trans <- transform(m_ncfs_comp, transFuncts)

The error I get is:
error in logicle_transform(as.double(x), as.double(t), as.double(w), as.double(m), :
Logicle Exception: DidNotConverge: scale() didn't converge

 Unfortunately I have no idea what to look at exactly to solve this. Might there be a problem with the fcs files itself or maybe with our template?

**Comment by gfinak** [comment]
What channels are you transforming and what is the range of the data in
those channels? You may want to consider filtering out events with extreme
negative values to see if that helps.
If you still have issues, consider posting one of the offending FCS files,
we can help to debug.

**Comment by kratschie** [comment]
Since I could not fix my problem, I am attaching  our template. Unfortunately my fcs files are too big (65MB each) for posting here.
[neu_fj_template.xlsx](https://github.com/RGLab/flowCore/files/818634/neu_fj_template.xlsx)


Thanks for your support!

**Comment by mikejiang** [comment]
Try a different sample other than the first one to estimate logicle parameters to see if it helps, e.g. pick the `3rd` sample
`transFuncts <- estimateLogicle(ncfs[[3]], channels = chnls)`

**Comment by kratschie** [comment]
I tried your suggested approach before. Unfortunately it does bring up the exact same error message.

**Comment by mikejiang** [comment]
this link is not working

**Comment by kratschie** [comment]
I updated it.

**Comment by mikejiang** [comment]
It worked for me and did not produce the error. It could be the compensation matrix you used is different from mine, or it is the another FCS that failed.
```r
fr <- read.FCS("KM503_1_E6C10.fcs")
comp <- spillover(fr)[[3]]
fr <- compensate(fr, comp)
chnl <- colnames(comp)
trans <- estimateLogicle(fr, chnl)
fr <- transform(fr, trans)
```
Also please check if all your packages are up to date (post your `sessionInfo()`)

**Comment by kratschie** [comment]
I updated my packages. It seems like the provided file is not recognized as a valid fcs file anymore(I am not sure, what the explanation would be), so I am  using a different one that was produced in the same run and it does work.
Thank you!

Now I get to work with the template I generated before and and keep having the same problem:
`multiple markers matched: CD3`

I worked with this [tutorial](https://github.com/RGLab/openCyto/blob/trunk/vignettes/HowToWriteCSVTemplate.Rmd)

I tried different approaches with CD3+/- but it seems like I misunderstood the main point in generating the [template](https://drive.google.com/open?id=0B9dfegwM-RmfMTgyVnVyRkhST1U) the correct way, cause I also get the mistake with CD4 and so on as well.

Thanks for your great support!

**Comment by mikejiang** [comment]
First of all, I read your FCS without problem, please check your `flowCore` version to see if it is the latest release.

Secondly, you seems to be reading the source code ( `R markdown` ) of the tutorial, please look at https://bioconductor.org/packages/release/bioc/vignettes/openCyto/inst/doc/HowToWriteCSVTemplate.html instead

You didn't set the `alias` and `dims` properly in your csv,(unsurprisingly, if you haven't read the right tutorial) e.g.
![image](https://cloud.githubusercontent.com/assets/1385649/23671340/baff17fa-031f-11e7-9856-f985a9c9a0d6.png)
In the 3rd row, you should leave `alias` as `*`  since it will be automatically expanded as `CD3+` and `CD3-` given the `pop` pattern you've set. Also `dims` should be simply `CD3`.
Actually based on your csv, I don't really see the need for populations `CD3-` and `CD4-`, so you may simply set `pop = CD3+` and `alias = CD3`. 
There are many other errors in your csv as well, I can't really tell what exactly you were trying to do because the `dims` column seems to be completely mismatched to the actual populations. So please spend some time on the tutorial.

**Comment by kratschie** [comment]
Thanks! I'll get back to you, as soon as more questions come up.

**Comment by kratschie** [comment]
Hello, I've been working on creating a template some more. I've used templateGen() and filled in gating methods and args. However, since I am not the one doing the manual gating so far, but only trying to understand what someone else has been doing I am still having quite a hard time here. 
[manual_template.txt](https://github.com/RGLab/flowCore/files/1137083/manual_template.txt)

A this point I am getting a ".preprocess_row(this_row, strict = strict) : 
  invalid population pattern 'CD27-CD38-HLADR-Ki67-'"error (this line was generated via templateGen()). Also I am very unsure of what args should added. 
Can you give me a hand in doing this right?
Thanks.

**Comment by gfinak** [comment]
I'm unable to read your file due to invalid characters. 
Your problem arises due to multiple minus and multiple plus signs in your population names in the pop column. The +/- signs are reserved for  openCyto to define populations based on channels.
You could do something like replace the - with an "n" and the + with a "p" in the pop and alias columns. This is specifically an issue with your boolean population definitions.
You have boundary gates set for CD4, CD3, CD27All, IFNg, HLADR, CD38, CD27, Ki67. These are probably not going to help you define the positive and negative populations. Since you are gating marginally, use something like mindensity. You will have to play with the gating parameters (this is not trivial). 
The boundary gates are still important, and you'll want to include those to eliminate boundary events.
I would also suggest defining the booleans computationally after gating all marginal populations. 
Finally all your marginal gate definitions should appear before the booleans, since the booleans depend on them.

Perhaps a good place to start is with a single line in your template, applied to one file. 
Verify that it works, and build up from there.
Trying to do everything at once, there are too many moving parts to isolate any specific problems.

**Comment by kratschie** [comment]
Thanks.  That was some great advice(for a beginner like me). Attached are plots of the gated data. I stayed with boundary for this first try (openCyto), which is not too bad compared to flowjo(especially since the population are not displayed that well in flowjo). secondly I tried exchenging boundary with mindensity, which led to an error: Gating for 'IFng+'
Fehler in (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  : failed at MB115... and : 
Error in seq_len(num_peaks)
<img width="562" alt="flowjo" src="https://user-images.githubusercontent.com/1489867/28044287-d1fd26f8-65d6-11e7-8810-3bdb573e35f6.png">
<img width="674" alt="opencyto" src="https://user-images.githubusercontent.com/1489867/28044298-dced4eb2-65d6-11e7-82a3-706265b93076.png">
![mind](https://user-images.githubusercontent.com/1489867/28044309-e8926a18-65d6-11e7-9b7a-892163c8c8f8.png)

I am having trouble deciding on a gating_method for every population, since in our lab they usually do polygons and I am not quite sure what gating_methods there are. I worked through "How to use different auto gating functions", but it does not include boolGate for example. 

 I was hoping to get more insight by loading the "manual.xml"file (from the flowWorkspaceData package )into flowjo, but it just gives me an error: Error adding files. 

DO you have any further suggestions? Thanks!

**Comment by gfinak** [comment]
@kratschie  
Sorry I did not respond sooner.
I just saw the plots you uploaded, and notice there are a lot of events on the boundary. 
Are you sure that the data are properly transformed? 
I tried to download the FCS file linked above but could not. Would you be able to reupload it? I'd like to have a quick look.
Best
Greg
