### ISSUE TITLE
R3.4.2 cannot install "flowCore" probably come from fortran library issue.

### ISSUE THREAD

**Issue by tkosaka1976** [RGLab/flowCore#88]
I have this error message when install "flowCore"

~~~
installing to /usr/local/lib/R/3.4/site-library/flowCore/libs
** R
** data
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
   共有ライブラリ '/usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so' を読み込めません:
  dlopen(/usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so
  Reason: image not found
ERROR: lazy loading failed for package ‘flowCore’
* removing ‘/usr/local/lib/R/3.4/site-library/flowCore’
~~~

I'm using Homebrew 1.3.4-61-gec0d8fa, and latest gcc (including gfortran 7.2.0).
Do you know good solution?

And this problem is probably related to [rigraph issue #191](https://github.com/igraph/rigraph/issues/191)

**Comment by gfinak** [comment]
This is not a flowCore issue. The mvtnorm library is not part of flowCore. This is a toolchain issue. The linker finds the mvtnorm library but can't use it. I don't know how you've set up your system, so I can't really help you, and this is not the venue for that anyway.  Since you are using a different compiler than what Apple distributes, my first instinct would be to build all R packages from source and forego binaries.  More instructions on installing R on Mac OS X are here:
https://cran.r-project.org/bin/macosx/
They state that you should be using clang4 if you're using the binary install. 
I'm closing this issue, perhaps move your question over to the BioConductor or R mailing list.

**Comment by tkosaka1976** [comment]
Thanks @gfinak!
I will inform this problem to homebrew-core.
